# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 93a660b97c46680f7f184eaa76f6e3a08c8ce1571ef1c6ae1f7171f149b0ee954f1f0517230b332e81c3253aed4eba2335ac16b1c86e9094b7f75ec28190ccf9

test:
  secret_key_base: 1262f8bbe5c0e7d16e5cb5c7851ee7699fe1c165c4873c319545fc8de8939facf23da648c5d51aced5f06b96a32ff960dd889ccff95ab253e0e0472752f3d1ef

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
